---
name: My Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.names_output.outputs.paths }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Run script with changes
      id: names_output
      run: |
        echo  "paths=[$(git diff --name-only -r HEAD^1 HEAD | grep env | cut -d/ -f1 | uniq | tr '\n' , | sed -e '$s/,$//')]" >> "$GITHUB_OUTPUT"

  other:
    runs-on: ubuntu-latest
    needs: my_job
    steps:
      - name: Print names
        run: |
         echo "${{ needs.my_job.outputs.names  }}"

  # print_names:
  #   needs: my_job
  #   strategy:
  #     matrix:
  #       name: ${{ needs.my_job.outputs.paths }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print name
  #       run: |
  #         cat ./${{ matrix.name }}/main.sh

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}

        run: echo "$OUTPUT1 $OUTPUT2"