---
name: My Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.names_output.outputs.paths }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Run script with changes
      id: names_output
      run: |
        echo paths=$(git diff --name-only -r HEAD^1 HEAD | grep env | cut -d/ -f1 | sort -u | jq -R -s 'split("\n")[:-1] | map({"name": .})') >> "$GITHUB_OUTPUT"

  other:
    runs-on: ubuntu-latest
    needs: my_job
    steps:
      - name: Print names
        run: |
         echo "${{ needs.my_job.outputs.names  }}"

  print_names:
    needs: my_job
    strategy:
      matrix: ${{ fromJSON(  needs.my_job.outputs.names ) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print name
        run: |
          cat ./${{ matrix.name }}/main.sh