---
name: My Workflow

on:
  push:
    paths:
    - '**' # Watch for changes in any path

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changes
      run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

