---
name: My Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Get changes
      run: git diff --name-only -r HEAD^1 HEAD

